name: Vitest Coverage

on:
  release:
    types: [published]
  workflow_dispatch:   

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run coverage
        run: npm run coverage

      - name: Zip coverage folder
        run: zip -r coverage.zip ./coverage

      - name: Upload coverage to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./coverage.zip
          asset_name: coverage.zip
          asset_content_type: application/zip
